-- Generated by cmux-evidence data refresh. Do not edit by hand.
-- Source file: data/tlc/reference/taxi_zone_lookup.csv
select *
from read_csv_auto('workspace-data/tlc/reference/taxi_zone_lookup.csv')
