-- Generated by cmux-evidence data refresh. Do not edit by hand.
-- Source file: data/tlc/raw/yellow/yellow_tripdata_2024-02.parquet
select *
from read_parquet('workspace-data/tlc/raw/yellow/yellow_tripdata_2024-02.parquet')
