#!/usr/bin/env python3
"""Workspace data registry: scan files, maintain registry, generate Evidence source SQL.

This module is the testable core of the workspace data registry feature.
It is imported by bin/cmux-evidence for CLI commands and can be tested independently.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import stat
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DATA_REGISTRY_FILENAME = "data-registry.json"
DATA_PROFILE_FILENAME = "data-profile.json"
DATA_DIR_NAME = "data"
GENERATED_FILES_SOURCE_NAME = "files"
GENERATED_HEADER = "-- Generated by cmux-evidence data refresh. Do not edit by hand."
MAX_SCAN_DEPTH = 5
SUPPORTED_EXTENSIONS = {".csv", ".tsv", ".parquet", ".json", ".jsonl"}
IGNORED_FILENAMES = {".ds_store", "thumbs.db", ".gitkeep"}
IGNORED_PREFIXES = (".", "~")


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

def workspace_data_dir(workspace_root: Path) -> Path:
    return workspace_root / DATA_DIR_NAME


def data_registry_path(workspace_root: Path) -> Path:
    return workspace_root / ".cmux" / DATA_REGISTRY_FILENAME


def data_profile_path(workspace_root: Path) -> Path:
    return workspace_root / ".cmux" / DATA_PROFILE_FILENAME


# ---------------------------------------------------------------------------
# Alias logic
# ---------------------------------------------------------------------------

def slugify_table_alias(filename: str) -> str:
    """Derive a stable alias from a filename stem.

    >>> slugify_table_alias("Monthly Sales 2026.csv")
    'monthly_sales_2026'
    >>> slugify_table_alias("123_data.csv")
    'table_123_data'
    >>> slugify_table_alias("---.csv")
    'data_file'
    """
    stem = Path(filename).stem
    # Lowercase
    alias = stem.lower()
    # Replace non-alphanumeric runs with _
    alias = re.sub(r"[^a-z0-9]+", "_", alias)
    # Trim leading/trailing underscores
    alias = alias.strip("_")
    # Fallback
    if not alias:
        alias = "data_file"
    # Prefix if starts with digit
    if alias[0].isdigit():
        alias = f"table_{alias}"
    return alias


def unique_alias(base_alias: str, used_aliases: set[str]) -> str:
    """Resolve alias collisions by appending _2, _3, etc."""
    if base_alias not in used_aliases:
        return base_alias
    i = 2
    while f"{base_alias}_{i}" in used_aliases:
        i += 1
    return f"{base_alias}_{i}"


# ---------------------------------------------------------------------------
# Fingerprint
# ---------------------------------------------------------------------------

def fingerprint_file(path: Path) -> str:
    """Produce a lightweight fingerprint from size + mtime."""
    try:
        s = path.stat()
        size = s.st_size
        mtime = datetime.fromtimestamp(s.st_mtime, tz=timezone.utc).isoformat()
        return f"size:{size};mtime:{mtime}"
    except OSError:
        return "size:0;mtime:1970-01-01T00:00:00+00:00"


# ---------------------------------------------------------------------------
# File scanning
# ---------------------------------------------------------------------------

def _should_ignore(name: str) -> bool:
    lower = name.lower()
    if lower in IGNORED_FILENAMES:
        return True
    if any(lower.startswith(p) for p in IGNORED_PREFIXES):
        return True
    return False


def scan_workspace_data_files(workspace_root: Path) -> list[dict[str, Any]]:
    """Scan workspace data directory for supported files.

    Returns a list of dicts with keys: path, format, size_bytes.
    Paths are workspace-relative (e.g. "data/orders.csv").
    """
    data_dir = workspace_data_dir(workspace_root)
    if not data_dir.is_dir():
        return []

    results: list[dict[str, Any]] = []

    def _visit(current: Path, depth: int) -> None:
        if depth > MAX_SCAN_DEPTH:
            return
        try:
            entries = sorted(current.iterdir())
        except OSError:
            return
        for entry in entries:
            if entry.name.startswith("."):
                continue
            if _should_ignore(entry.name):
                continue
            if entry.is_dir():
                _visit(entry, depth + 1)
            elif entry.is_file():
                ext = entry.suffix.lower()
                if ext not in SUPPORTED_EXTENSIONS:
                    continue
                try:
                    size = entry.stat().st_size
                except OSError:
                    size = 0
                rel = str(entry.relative_to(workspace_root))
                fmt = _format_from_ext(ext)
                results.append({
                    "path": rel,
                    "format": fmt,
                    "size_bytes": size,
                })

    _visit(data_dir, 0)
    return sorted(results, key=lambda f: f["path"])


def _format_from_ext(ext: str) -> str:
    mapping = {
        ".csv": "csv",
        ".tsv": "tsv",
        ".parquet": "parquet",
        ".json": "json",
        ".jsonl": "jsonl",
    }
    return mapping.get(ext, "unknown")


# ---------------------------------------------------------------------------
# Registry operations
# ---------------------------------------------------------------------------

def load_data_registry(workspace_root: Path) -> dict[str, Any]:
    """Load existing registry or return empty structure."""
    path = data_registry_path(workspace_root)
    if not path.exists():
        return _empty_registry(workspace_root)
    try:
        data = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return _empty_registry(workspace_root)
    if not isinstance(data, dict):
        return _empty_registry(workspace_root)
    data.setdefault("version", 1)
    data.setdefault("sourceName", GENERATED_FILES_SOURCE_NAME)
    data.setdefault("tables", [])
    data.setdefault("warnings", [])
    return data


def save_data_registry(workspace_root: Path, registry: dict[str, Any]) -> None:
    """Write registry atomically."""
    path = data_registry_path(workspace_root)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(registry, indent=2, sort_keys=True) + "\n")
    tmp.replace(path)


def _empty_registry(workspace_root: Path) -> dict[str, Any]:
    return {
        "version": 1,
        "sourceName": GENERATED_FILES_SOURCE_NAME,
        "workspaceRoot": str(workspace_root.resolve()),
        "updatedAt": _now_iso(),
        "tables": [],
        "warnings": [],
    }


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# ---------------------------------------------------------------------------
# Refresh
# ---------------------------------------------------------------------------

def refresh_workspace_data_registry(
    workspace_root: Path,
    *,
    profile: bool = False,
) -> dict[str, Any]:
    """Scan data files, update registry, return the updated registry.

    - Preserves existing aliases for the same file path.
    - Marks missing files with status "missing".
    - Adds new files with status "ready".
    - Does NOT generate source SQL (call generate_workspace_file_sources separately).
    """
    existing = load_data_registry(workspace_root)
    existing_by_path: dict[str, dict[str, Any]] = {}
    for table in existing.get("tables", []):
        p = table.get("path", "")
        if p:
            existing_by_path[p] = table

    files = scan_workspace_data_files(workspace_root)
    existing_paths = {f["path"] for f in files}

    # Build new tables list
    used_aliases: set[str] = set()
    new_tables: list[dict[str, Any]] = []

    # First pass: preserve existing entries for files that still exist
    for f in files:
        old = existing_by_path.get(f["path"])
        if old:
            alias = old.get("alias", slugify_table_alias(f["path"]))
            new_tables.append({
                "alias": alias,
                "qualifiedName": f"{GENERATED_FILES_SOURCE_NAME}.{alias}",
                "path": f["path"],
                "format": f["format"],
                "sizeBytes": f["size_bytes"],
                "fingerprint": fingerprint_file(workspace_root / f["path"]),
                "status": "ready",
                "columns": old.get("columns", []),
                "rowCount": old.get("rowCount"),
                "warnings": old.get("warnings", []),
            })
            used_aliases.add(alias)

    # Second pass: new files
    for f in files:
        if f["path"] in {t["path"] for t in new_tables}:
            continue
        base_alias = slugify_table_alias(Path(f["path"]).name)
        alias = unique_alias(base_alias, used_aliases)
        used_aliases.add(alias)
        new_tables.append({
            "alias": alias,
            "qualifiedName": f"{GENERATED_FILES_SOURCE_NAME}.{alias}",
            "path": f["path"],
            "format": f["format"],
            "sizeBytes": f["size_bytes"],
            "fingerprint": fingerprint_file(workspace_root / f["path"]),
            "status": "ready",
            "columns": [],
            "rowCount": None,
            "warnings": [],
        })

    # Mark missing files
    for path_key, old_table in existing_by_path.items():
        if path_key not in existing_paths:
            old_table["status"] = "missing"
            new_tables.append(old_table)

    registry = {
        "version": 1,
        "sourceName": GENERATED_FILES_SOURCE_NAME,
        "workspaceRoot": str(workspace_root.resolve()),
        "updatedAt": _now_iso(),
        "tables": new_tables,
        "warnings": [],
    }

    save_data_registry(workspace_root, registry)
    return registry


# ---------------------------------------------------------------------------
# Source SQL generation
# ---------------------------------------------------------------------------

def generate_workspace_file_sources(
    workspace_root: Path,
    shadow_root: Path,
    registry: dict[str, Any],
) -> None:
    """Generate Evidence source SQL files under shadow_root/sources/files/."""
    files_dir = shadow_root / "sources" / GENERATED_FILES_SOURCE_NAME
    files_dir.mkdir(parents=True, exist_ok=True)

    # Generate connection.yaml
    connection_content = (
        f"{GENERATED_HEADER}\n"
        f"name: {GENERATED_FILES_SOURCE_NAME}\n"
        f"type: duckdb\n"
        f"options:\n"
        f'  filename: ":memory:"\n'
    )
    (files_dir / "connection.yaml").write_text(connection_content)

    # Remove any existing generated .sql files (clean regeneration)
    for old_sql in files_dir.glob("*.sql"):
        old_sql.unlink(missing_ok=True)

    # Generate one .sql per ready table
    ready_tables = [t for t in registry.get("tables", []) if t.get("status") == "ready"]
    for table in ready_tables:
        alias = table["alias"]
        file_path = table["path"]
        fmt = table.get("format", "csv")

        # Build the SQL — reference workspace-data symlink
        sql = _generated_sql(alias, file_path, fmt)
        (files_dir / f"{alias}.sql").write_text(sql)


def _generated_sql(alias: str, file_path: str, fmt: str) -> str:
    """Generate the SQL content for a single source file."""
    # The shadow runtime has workspace-data -> workspace/data
    shadow_rel = f"workspace-data/{file_path.removeprefix('data/')}"
    source_file_comment = f"-- Source file: {file_path}"

    if fmt == "csv":
        body = f"select *\nfrom read_csv_auto('{shadow_rel}')"
    elif fmt == "tsv":
        body = f"select *\nfrom read_csv_auto('{shadow_rel}', delim='\\t')"
    elif fmt == "parquet":
        body = f"select *\nfrom read_parquet('{shadow_rel}')"
    elif fmt in ("json", "jsonl"):
        body = f"select *\nfrom read_json_auto('{shadow_rel}')"
    else:
        body = f"select *\nfrom read_csv_auto('{shadow_rel}')"

    return f"{GENERATED_HEADER}\n{source_file_comment}\n{body}\n"


# ---------------------------------------------------------------------------
# Summary output
# ---------------------------------------------------------------------------

def print_registry_summary(registry: dict[str, Any]) -> str:
    """Return a human-readable summary of the registry."""
    tables = registry.get("tables", [])
    if not tables:
        return (
            "No workspace data files found.\n\n"
            "Add files under:\n  data/\n\n"
            "Supported formats:\n"
            "  .csv, .tsv, .parquet, .json, .jsonl\n\n"
            "No Evidence source files were generated."
        )

    lines = ["Workspace data refreshed.", "", "Registered tables:"]
    for t in tables:
        status = t.get("status", "unknown")
        name = f"files.{t['alias']}"
        path = t.get("path", "")
        lines.append(f"  {name:<24} {path:<30} {status}")

    # List generated source files
    source_names = [f"{t['alias']}.sql" for t in tables if t.get("status") == "ready"]
    if source_names:
        lines.append("")
        lines.append("Generated Evidence source files:")
        lines.append(f"  sources/{GENERATED_FILES_SOURCE_NAME}/connection.yaml")
        for name in source_names:
            lines.append(f"  sources/{GENERATED_FILES_SOURCE_NAME}/{name}")

    lines.append("")
    lines.append("Next:")
    ready_names = [f"files.{t['alias']}" for t in tables if t.get("status") == "ready"]
    if ready_names:
        lines.append(f"  Use {' and '.join(ready_names)} in Evidence page SQL.")
    else:
        lines.append("  No ready tables. Check file formats and try again.")

    return "\n".join(lines)


def print_list_summary(registry: dict[str, Any]) -> str:
    """Return formatted output for 'data list'."""
    tables = registry.get("tables", [])
    if not tables:
        # Check if there's a data dir with files but no registry
        return (
            "No workspace data registry found.\n"
            "Add files under data/ and run:\n"
            "  cmux-evidence data refresh"
        )

    lines = ["", "Registered workspace data", ""]
    for t in tables:
        alias = f"files.{t['alias']}"
        lines.append(alias)
        lines.append(f"  Path: {t.get('path', '?')}")
        lines.append(f"  Format: {t.get('format', '?')}")
        lines.append(f"  Status: {t.get('status', '?')}")
        if t.get("rowCount") is not None:
            lines.append(f"  Rows: {t['rowCount']:,}")
        if t.get("columns"):
            col_names = [c.get("name", "?") for c in t["columns"]]
            lines.append(f"  Columns: {', '.join(col_names)}")
        lines.append("")

    return "\n".join(lines).rstrip()
